import { ASTNode } from "../core/CAstNode/ASTNode";
import { CompoundStmt } from "../core/CAstNode/CompoundStmt";
import { ConstantExpr } from "../core/CAstNode/ConstantExpr";
import { ElaboratedType } from "../core/CAstNode/ElaboratedType";
import { EnumConstantDecl } from "../core/CAstNode/EnumConstantDecl";
import { EnumDecl } from "../core/CAstNode/EnumDecl";
import { FunctionDecl } from "../core/CAstNode/FunctionDecl";
import { ParmVarDecl } from "../core/CAstNode/ParmVarDecl";
import { TypedefDecl } from "../core/CAstNode/TypedefDecl";
import { NodeFactoryMgr } from "../core/Manager/NodeFactoryMgr";
import { SynxType } from "../core/SynxType";

NodeFactoryMgr.instance.regCreator(SynxType.Unknown, ASTNode);
NodeFactoryMgr.instance.regCreator(SynxType.EnumDecl, EnumDecl);
NodeFactoryMgr.instance.regCreator(SynxType.EnumConstantDecl, EnumConstantDecl);
NodeFactoryMgr.instance.regCreator(SynxType.TypedefDecl, TypedefDecl);
NodeFactoryMgr.instance.regCreator(SynxType.ConstantExpr, ConstantExpr);
NodeFactoryMgr.instance.regCreator(SynxType.ElaboratedType, ElaboratedType);
NodeFactoryMgr.instance.regCreator(SynxType.FunctionDecl, FunctionDecl);
NodeFactoryMgr.instance.regCreator(SynxType.ParmVarDecl, ParmVarDecl);
NodeFactoryMgr.instance.regCreator(SynxType.CompoundStmt, CompoundStmt);
