import { TransformerMgr } from "../core/Manager/TransformerMgr";
import { SynxType } from "../core/SynxType";
import { TransformerCaseStmt } from "../core/Transformers/TransformerCaseStmt";
import { TransformerCompoundStmt } from "../core/Transformers/TransformerCompoundStmt";
import { TransformerDeclStmt } from "../core/Transformers/TransformerDeclStmt";
import { TransformerEnumDecl } from "../core/Transformers/TransformerEnumDecl";
import { TransformerForStmt } from "../core/Transformers/TransformerForStmt";
import { TransformerFunctionDecl } from "../core/Transformers/TransformerFunctionDecl";
import { TransformerIfStmt } from "../core/Transformers/TransformerIfStmt";
import { TransformerRecordDecl } from "../core/Transformers/TransformerRecordDecl";
import { TransformerSwitchStmt } from "../core/Transformers/TransformerSwitchStmt";
import { TransformerTypedefDecl } from "../core/Transformers/TransformerTypeDecl";
import { TransformerVarDecl } from "../core/Transformers/TransformerVarDecl";

TransformerMgr.instance.regTransformer(SynxType.EnumDecl, new TransformerEnumDecl());
TransformerMgr.instance.regTransformer(SynxType.FunctionDecl, new TransformerFunctionDecl());
TransformerMgr.instance.regTransformer(SynxType.TypedefDecl, new TransformerTypedefDecl());
TransformerMgr.instance.regTransformer(SynxType.DeclStmt, new TransformerDeclStmt());
TransformerMgr.instance.regTransformer(SynxType.IfStmt, new TransformerIfStmt());
TransformerMgr.instance.regTransformer(SynxType.SwitchStmt, new TransformerSwitchStmt());
TransformerMgr.instance.regTransformer(SynxType.CaseStmt, new TransformerCaseStmt());
TransformerMgr.instance.regTransformer(SynxType.ForStmt, new TransformerForStmt());
TransformerMgr.instance.regTransformer(SynxType.VarDecl, new TransformerVarDecl());
TransformerMgr.instance.regTransformer(SynxType.CompoundStmt, new TransformerCompoundStmt());
TransformerMgr.instance.regTransformer(SynxType.RecordDecl, new TransformerRecordDecl());
