import { ASTNode } from "../core/CAstNode/ASTNode";
import { BinaryOperator } from "../core/CAstNode/BinaryOperator";
import { CallExpr } from "../core/CAstNode/CallExpr";
import { CaseStmt } from "../core/CAstNode/CaseStmt";
import { CompoundStmt } from "../core/CAstNode/CompoundStmt";
import { ConstantExpr } from "../core/CAstNode/ConstantExpr";
import { DeclStmt } from "../core/CAstNode/DeclStmt";
import { ElaboratedType } from "../core/CAstNode/ElaboratedType";
import { EnumConstantDecl } from "../core/CAstNode/EnumConstantDecl";
import { EnumDecl } from "../core/CAstNode/EnumDecl";
import { FieldDecl } from "../core/CAstNode/FieldDecl";
import { ForStmt } from "../core/CAstNode/ForStmt";
import { FunctionDecl } from "../core/CAstNode/FunctionDecl";
import { IfStmt } from "../core/CAstNode/IfStmt";
import { IntegerLiteral } from "../core/CAstNode/IntegerLiteral";
import { ParmVarDecl } from "../core/CAstNode/ParmVarDecl";
import { RecordDecl } from "../core/CAstNode/RecordDecl";
import { ReturnStmt } from "../core/CAstNode/ReturnStmt";
import { SwitchStmt } from "../core/CAstNode/SwitchStmt";
import { TypedefDecl } from "../core/CAstNode/TypedefDecl";
import { VarDecl } from "../core/CAstNode/VarDecl";
import { NodeFactoryMgr } from "../core/Manager/NodeFactoryMgr";
import { SynxType } from "../core/SynxType";

NodeFactoryMgr.instance.regCreator(SynxType.Unknown, ASTNode);
NodeFactoryMgr.instance.regCreator(SynxType.EnumDecl, EnumDecl);
NodeFactoryMgr.instance.regCreator(SynxType.EnumConstantDecl, EnumConstantDecl);
NodeFactoryMgr.instance.regCreator(SynxType.TypedefDecl, TypedefDecl);
NodeFactoryMgr.instance.regCreator(SynxType.ConstantExpr, ConstantExpr);
NodeFactoryMgr.instance.regCreator(SynxType.ElaboratedType, ElaboratedType);
NodeFactoryMgr.instance.regCreator(SynxType.FunctionDecl, FunctionDecl);
NodeFactoryMgr.instance.regCreator(SynxType.ParmVarDecl, ParmVarDecl);
NodeFactoryMgr.instance.regCreator(SynxType.DeclStmt, DeclStmt);
NodeFactoryMgr.instance.regCreator(SynxType.IfStmt, IfStmt);
NodeFactoryMgr.instance.regCreator(SynxType.SwitchStmt, SwitchStmt);
NodeFactoryMgr.instance.regCreator(SynxType.CaseStmt, CaseStmt);
NodeFactoryMgr.instance.regCreator(SynxType.VarDecl, VarDecl);
NodeFactoryMgr.instance.regCreator(SynxType.CompoundStmt, CompoundStmt);
NodeFactoryMgr.instance.regCreator(SynxType.IntegerLiteral, IntegerLiteral);
NodeFactoryMgr.instance.regCreator(SynxType.ForStmt, ForStmt);
NodeFactoryMgr.instance.regCreator(SynxType.ReturnStmt, ReturnStmt);
NodeFactoryMgr.instance.regCreator(SynxType.BinaryOperator, BinaryOperator);
NodeFactoryMgr.instance.regCreator(SynxType.RecordDecl, RecordDecl);
NodeFactoryMgr.instance.regCreator(SynxType.FieldDecl, FieldDecl);
NodeFactoryMgr.instance.regCreator(SynxType.CallExpr, CallExpr);
