export function window_building_draw_academy(..._args: any[]): any { return 0; }
export function window_building_draw_actor_colony(..._args: any[]): any { return 0; }
export function window_building_draw_amphitheater(..._args: any[]): any { return 0; }
export function window_building_draw_barber(..._args: any[]): any { return 0; }
export function window_building_draw_bathhouse(..._args: any[]): any { return 0; }
export function window_building_draw_chariot_maker(..._args: any[]): any { return 0; }
export function window_building_draw_clinic(..._args: any[]): any { return 0; }
export function window_building_draw_colosseum(..._args: any[]): any { return 0; }
export function window_building_draw_gladiator_school(..._args: any[]): any { return 0; }
export function window_building_draw_hippodrome(..._args: any[]): any { return 0; }
export function window_building_draw_hospital(..._args: any[]): any { return 0; }
export function window_building_draw_library(..._args: any[]): any { return 0; }
export function window_building_draw_lion_house(..._args: any[]): any { return 0; }
export function window_building_draw_oracle(..._args: any[]): any { return 0; }
export function window_building_draw_school(..._args: any[]): any { return 0; }
export function window_building_draw_temple_ceres(..._args: any[]): any { return 0; }
export function window_building_draw_temple_mars(..._args: any[]): any { return 0; }
export function window_building_draw_temple_mercury(..._args: any[]): any { return 0; }
export function window_building_draw_temple_neptune(..._args: any[]): any { return 0; }
export function window_building_draw_temple_venus(..._args: any[]): any { return 0; }
export function window_building_draw_theater(..._args: any[]): any { return 0; }
