
export const enum sound_channel {
    SOUND_CHANNEL_SPEECH = 0,
    SOUND_CHANNEL_EFFECTS_MIN = 1,
    SOUND_CHANNEL_EFFECTS_MAX = 44,
    SOUND_CHANNEL_CITY_MIN = 45,
    SOUND_CHANNEL_CITY_MAX = 148,
    SOUND_CHANNEL_MAX = 149,
}
